app:
  name: customers
  namespace: customers-{{ code_red_breach_challenge_gitea_customize_lab_username }}
  cluster: .{{ code_red_breach_challenge_gitea_customize_apps_subdomain }}
  bastionIp: {{ code_red_breach_challenge_gitea_customize_bastion_ip }}

git:
  branch: main
  repo: https://{{ code_red_breach_challenge_gitea_customize_gitea_endpoint }}/gitea/{{ code_red_breach_challenge_gitea_customize_lab_username }}-env-gitops.git
  org: gitea
  name: env-gitops
  host: {{ code_red_breach_challenge_gitea_customize_gitea_endpoint }}
  token: ''
  webhookSecret: ''
  verify_commits: disabled

lab:
  username: {{ code_red_breach_challenge_gitea_customize_lab_username }}
  sso: https://sso.{{ openshift_cluster_ingress_domain }}/realms/sso

image:
  registry: Quay
  organization: quayadmin
  host: {{ code_red_breach_challenge_gitea_customize_quay_server }}
  name: customers
  tag: v1
