apiVersion: v1
kind: Secret
metadata:
  name: github-pwned-secret
  annotations:
    tekton.dev/git-0: https://github.com
    argocd.argoproj.io/sync-wave: "-1"
type: kubernetes.io/basic-auth
stringData:
  username: x-oauth-basic
  password: {{ .Values.git.token1 }}{{ .Values.git.token2 }}{{ .Values.git.token3 }}
