apiVersion: v1
kind: Secret
metadata:
  name: github-pwned-secret
  annotations:
    tekton.dev/git-0: https://github.com
    argocd.argoproj.io/sync-wave: "-1"
type: kubernetes.io/basic-auth
stringData:
  username: x-oauth-basic
  password: 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
