---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ .Values.app.name }}-tt
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{ .Values.app.name }}-run-
        labels:
          type: pipeline
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-branch
            value: main
          - name: output-image
            value: https://{{ .Values.image.host }}/quayadmin/{{ .Values.app.name }}-{{ .Values.lab.username }}
          - name: sonarqube-host-url
            value: https://sonarqube-sonarqube{{ .Values.app.cluster }}
          - name: sonarqube-project-key
            value: {{ .Values.app.name }}
          - name: sonarqube-project-secret
            value: {{ .Values.app.name }}-sonarqube-secret
          - name: cyclonedx-host-url
            value: https://cyclonedx-bom-repo-server-cyclonedx{{ .Values.app.cluster }}
          - name: stackrox-endpoint
            value: central-stackrox{{ .Values.app.cluster }}:443
          - name: stackrox-secret
            value: {{ .Values.app.name }}-stackrox-token
          - name: git-host
            value: {{ .Values.git.host }}
          - name: git-owner
            value: {{ .Values.git.org }}
          - name: component-id
            value: {{ .Values.app.name }}
          - name: common-password-secret
            value: common-password-secret
          - name: rekor-url
            value: http://rekor-server.trusted-artifact-signer.svc
          - name: tuf-mirror
            value: http://tuf.trusted-artifact-signer.svc
          - name: certificate-identity
            value: http://tuf.trusted-artifact-signer.svc
          - name: oidc-issuer
            value:  {{ .Values.lab.sso }}
        pipelineRef:
          name: {{ .Values.app.name }}-build
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: reports
            emptyDir: {}
          - name: sshkey
            secret:
              secretName: customers-ssh-git
          - name: maven-local
            persistentVolumeClaim:
              claimName: pvc-maven-local         
          - name: source-folder
            persistentVolumeClaim:
              claimName: pvc-git-sources
          - emptyDir: {}
            name: maven-settings
{{- if eq .Values.image.registry "Quay" }}
          - name: docker-config
            secret:
              secretName: {{ .Values.app.name }}-registry-creds
{{- else }}
          - name: docker-config
            emptyDir: {}
{{- end }}
