apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  labels:
    operator.tekton.dev/operand-name: openshift-pipelines-addons
  name: git-push
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.url)
